version: '3.10'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: search_smartly
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin!@#$%^&*(
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - search-smartly-network


  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - search-smartly-network

networks:
  search-smartly-network:
    external: false
    name: search-smartly-network

volumes:
  pgdata:
    driver: local